//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortProcessManager.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortProcessManager.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 (管理员) 的本地化字符串。
        /// </summary>
        internal static string AdminLabel {
            get {
                return ResourceManager.GetString("AdminLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口进程管理器 的本地化字符串。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动刷新 (5s) 的本地化字符串。
        /// </summary>
        internal static string AutoRefresh {
            get {
                return ResourceManager.GetString("AutoRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地地址 的本地化字符串。
        /// </summary>
        internal static string ColumnLocalAddress {
            get {
                return ResourceManager.GetString("ColumnLocalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地端口 的本地化字符串。
        /// </summary>
        internal static string ColumnLocalPort {
            get {
                return ResourceManager.GetString("ColumnLocalPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径 的本地化字符串。
        /// </summary>
        internal static string ColumnPath {
            get {
                return ResourceManager.GetString("ColumnPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PID 的本地化字符串。
        /// </summary>
        internal static string ColumnPid {
            get {
                return ResourceManager.GetString("ColumnPid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进程 的本地化字符串。
        /// </summary>
        internal static string ColumnProcess {
            get {
                return ResourceManager.GetString("ColumnProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 协议 的本地化字符串。
        /// </summary>
        internal static string ColumnProtocol {
            get {
                return ResourceManager.GetString("ColumnProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 远程地址 的本地化字符串。
        /// </summary>
        internal static string ColumnRemoteAddress {
            get {
                return ResourceManager.GetString("ColumnRemoteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 远程端口 的本地化字符串。
        /// </summary>
        internal static string ColumnRemotePort {
            get {
                return ResourceManager.GetString("ColumnRemotePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        internal static string ColumnState {
            get {
                return ResourceManager.GetString("ColumnState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        internal static string ColumnUser {
            get {
                return ResourceManager.GetString("ColumnUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 个连接 的本地化字符串。
        /// </summary>
        internal static string ConnectionsCount {
            get {
                return ResourceManager.GetString("ConnectionsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制完整路径 的本地化字符串。
        /// </summary>
        internal static string CopyPath {
            get {
                return ResourceManager.GetString("CopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 PID 的本地化字符串。
        /// </summary>
        internal static string CopyPid {
            get {
                return ResourceManager.GetString("CopyPid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制端口 的本地化字符串。
        /// </summary>
        internal static string CopyPort {
            get {
                return ResourceManager.GetString("CopyPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量复制选中行 的本地化字符串。
        /// </summary>
        internal static string CopySelectedRows {
            get {
                return ResourceManager.GetString("CopySelectedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按进程分组 的本地化字符串。
        /// </summary>
        internal static string GroupByProcess {
            get {
                return ResourceManager.GetString("GroupByProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束该组进程 的本地化字符串。
        /// </summary>
        internal static string KillGroupProcess {
            get {
                return ResourceManager.GetString("KillGroupProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束选中进程 的本地化字符串。
        /// </summary>
        internal static string KillSelectedProcess {
            get {
                return ResourceManager.GetString("KillSelectedProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文 的本地化字符串。
        /// </summary>
        internal static string LanguageChinese {
            get {
                return ResourceManager.GetString("LanguageChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未发现匹配的端口占用 的本地化字符串。
        /// </summary>
        internal static string NoMatchingPorts {
            get {
                return ResourceManager.GetString("NoMatchingPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件位置 的本地化字符串。
        /// </summary>
        internal static string OpenFileLocation {
            get {
                return ResourceManager.GetString("OpenFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进程:  的本地化字符串。
        /// </summary>
        internal static string ProcessLabel {
            get {
                return ResourceManager.GetString("ProcessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 立即刷新 的本地化字符串。
        /// </summary>
        internal static string RefreshNow {
            get {
                return ResourceManager.GetString("RefreshNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在扫描系统端口... 的本地化字符串。
        /// </summary>
        internal static string ScanningPorts {
            get {
                return ResourceManager.GetString("ScanningPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TCP:  的本地化字符串。
        /// </summary>
        internal static string TcpLabel {
            get {
                return ResourceManager.GetString("TcpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总连接:  的本地化字符串。
        /// </summary>
        internal static string TotalConnections {
            get {
                return ResourceManager.GetString("TotalConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UDP:  的本地化字符串。
        /// </summary>
        internal static string UdpLabel {
            get {
                return ResourceManager.GetString("UdpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows 端口管理器 的本地化字符串。
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
